### ISSUE TITLE
support esp32 dlna render

### ISSUE THREAD

**Issue by 0neday** [yellobyte/SoapESP32#3]
hi, I have check your library, it could scan dlna server. 
but I have wonder know it could for dlna render? so that it cloud found by HA

**Comment by yellobyte** [comment]
Hi, pls have a look at https://github.com/yellobyte/ESP32-Webradio-PlusDLNA/blob/main/Software/src/main.cpp.
You will find an example of how to access a media server and read/play its audio files. Regards Th

**Comment by modi12jin** [comment]
@yellobyte Hi! excuse me. Can you make an example similar to the ADF example DLNA? Play music with your phone and computer

https://github.com/espressif/esp-adf/tree/master/examples/advanced_examples/dlna

**Comment by yellobyte** [comment]
Hi! Actually the library has no DLNA render functionality at all. It's aim is to provide basic SOAP functions (Simple Object Access Protocol), enabling you to find/browse a DLNA server and download media files. In order to play a media file you need media render hardware and then feed it with media content, which is outside the scope of this lib.
As I mentioned already in my comment from 14.April , please have a look at https://github.com/yellobyte/ESP32-Webradio-PlusDLNA which does basically what you want and gives you an idea how to do it. 
Regards Thomas

**Comment by modi12jin** [comment]
@yellobyte   Someone ported the ADF framework to the Arduino platform

【我成功将ESP-ADF移植到了Arduino上，并封装成ArduinoADFSimplify库，ESP32音频开发不再有门槛-哔哩哔哩】 https://b23.tv/h1f7luY
